# Generated by Django 4.1.5 on 2023-01-31 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalDetails',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=500)),
                ('bio', models.TextField()),
                ('profile_created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
