# Generated by Django 4.1.5 on 2023-01-31 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_name', models.CharField(max_length=200)),
                ('project_head', models.CharField(max_length=500)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_link', models.CharField(blank=True, max_length=5000, null=True)),
                ('project_youtube_link', models.CharField(blank=True, max_length=5000, null=True)),
                ('project_created', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectCatogery',
            fields=[
                ('project_catogery_name', models.CharField(max_length=500)),
                ('project_category_created', models.DateTimeField(auto_now_add=True)),
                ('project_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
